- src/cache/CacheInterface.php
- src/cache/CacheObject.php
- src/cache/RedisClient.php
> add Cache layer

- composer.json
- src/payload/AbstractPayload.php
- src/payload/AbstractResponseXmlPayload.php
- src/payload/AbstractXmlPayload.php
- src/payload/Payload.php
- src/payload/methods/req/activatePaymentNotice.php
- src/payload/methods/resp/activatePaymentNotice.php
- tests/bootstrap.php
- tests/phpunit.xml
- tests/template/common/fault.tpl
- tests/template/common/transfer.tpl
- tests/template/fault/activatePaymentNotice.tpl
- tests/template/req/activatePaymentNotice.tpl
- tests/template/resp/activatePaymentNotice.tpl
- tests/ut/payload/req/activatePaymentNoticeTest.php
- tests/ut/payload/resp/activatePaymentNoticeTest.php
> add layer xml, test for activatePaymentNotice

- src/events/AbstractEvent.php
- src/events/req/activatePaymentNotice.php
- src/events/resp/activatePaymentNotice.php
- tests/bootstrap.php
- tests/phpunit.xml
- tests/ut/events/req/activatePaymentNoticeTest.php
> add event layer

- src/payload/RequestXML.php
- src/payload/req/paGetPayment.php
- src/payload/resp/paGetPayment.php
- tests/payload/req/paGetPaymentTest.php
- tests/payload/resp/paGetPaymentTest.php
- tests/phpunit.xml
- tests/template/fault/paGetPayment.tpl
- tests/template/req/paGetPayment.tpl
- tests/template/resp/paGetPayment.tpl
> add paGetPayment

- src/payload/req/paVerifyPaymentNotice.php
- src/payload/resp/paVerifyPaymentNotice.php
- tests/payload/req/paVerifyPaymentNoticeTest.php
- tests/payload/resp/paVerifyPaymentNoticeTest.php
- tests/phpunit.xml
- tests/template/fault/paVerifyPaymentNotice.tpl
- tests/template/req/paVerifyPaymentNotice.tpl
- tests/template/resp/paVerifyPaymentNotice.tpl
> add paVerifyPaymentNotice

- src/payload/ParserInterface.php
- src/payload/RequestXML.php
- src/payload/ResponseXML.php
- src/payload/XmlParser.php
- src/payload/req/paSendRT.php
- src/payload/resp/paSendRT.php
- tests/payload/req/paSendRTTest.php
- tests/payload/resp/paSendRTTest.php
- tests/phpunit.xml
- tests/template/fault/paSendRT.tpl
- tests/template/req/paSendRT.tpl
- tests/template/resp/paSendRT.tpl
> add paSendRT

- src/payload/RequestXML.php
- src/payload/ResponseXML.php
- src/payload/XmlParser.php
- src/payload/req/activatePaymentNotice.php
- src/payload/req/activatePaymentNoticeV2.php
- src/payload/req/sendPaymentOutcome.php
- src/payload/req/verifyPaymentNotice.php
- src/payload/resp/activatePaymentNoticeV2.php
- src/payload/resp/paGetPayment.php
- tests/payload/req/activatePaymentNoticeV2Test.php
- tests/payload/resp/activatePaymentNoticeV2Test.php
- tests/phpunit.xml
- tests/template/common/transfer.tpl
- tests/template/fault/activatePaymentNoticeV2.tpl
- tests/template/req/activatePaymentNoticeV2.tpl
- tests/template/resp/activatePaymentNoticeV2.tpl
> add activateV2

- src/payload/req/paGetPaymentV2.php
- src/payload/resp/paGetPaymentV2.php
- tests/payload/req/paGetPaymentV2Test.php
- tests/payload/resp/activatePaymentNoticeV2Test.php
- tests/payload/resp/paGetPaymentV2Test.php
- tests/phpunit.xml
- tests/template/fault/paGetPaymentV2.tpl
- tests/template/req/paGetPaymentV2.tpl
- tests/template/resp/paGetPaymentV2.tpl
> add paGetPaymentV2

- src/payload/req/paSendRTV2.php
- src/payload/resp/paSendRTV2.php
- tests/payload/req/paSendRTV2Test.php
- tests/payload/resp/paSendRTV2Test.php
- tests/phpunit.xml
- tests/template/fault/paSendRTV2.tpl
- tests/template/req/paSendRTV2.tpl
- tests/template/resp/paSendRTV2.tpl
> add paSendRTV2

- tests/payload/resp/sendPaymentOutcomeV2Test.php
> fix test SPO

- src/payload/req/pspNotifyPayment.php
- src/payload/resp/pspNotifyPayment.php
- tests/payload/req/pspNotifyPaymentTest.php
- tests/payload/resp/pspNotifyPaymentTest.php
- tests/phpunit.xml
- tests/template/common/additionalPaymentInformation.tpl
- tests/template/common/bancomatPayPayment.tpl
- tests/template/common/creditCardPayment.tpl
- tests/template/common/paypalPayment.tpl
- tests/template/fault/pspNotifyPayment.tpl
- tests/template/req/pspNotifyPayment.tpl
- tests/template/resp/pspNotifyPayment.tpl
> add pspNotifyPaymentV1

- src/payload/req/pspNotifyPaymentV2.php
- src/payload/resp/pspNotifyPaymentV2.php
- tests/payload/req/pspNotifyPaymentV2Test.php
- tests/payload/resp/pspNotifyPaymentV2Test.php
- tests/phpunit.xml
- tests/template/common/payment.tpl
- tests/template/fault/pspNotifyPaymentV2.tpl
- tests/template/req/pspNotifyPaymentV2.tpl
- tests/template/resp/pspNotifyPaymentV2.tpl
> add pspNotifyPaymentV2

- src/payload/req/closePaymentV2.php
- src/payload/resp/closePaymentV2.php
- tests/payload/RequestJsonTest.php
- tests/payload/req/closePaymentV2Test.php
- tests/payload/resp/closePaymentV2Test.php
- tests/phpunit.xml
- tests/template/req/closePaymentV2.tpl
- tests/template/resp/closePaymentV2.tpl
> add closePaymentV2

- src/payload/req/activateIOPayment.php
- src/payload/resp/activateIOPayment.php
- tests/payload/req/activateIOPaymentTest.php
- tests/payload/resp/activateIOPaymentTest.php
- tests/phpunit.xml
- tests/template/fault/activateIOPayment.tpl
- tests/template/req/activateIOPayment.tpl
- tests/template/resp/activateIOPayment.tpl
> add activateIOPayment

- src/payload/object/RPT.php
- src/payload/object/RT.php
- tests/payload/object/RPTTest.php
- tests/payload/object/RTTest.php
- tests/phpunit.xml
- tests/template/common/versamenti_rpt.tpl
- tests/template/common/versamenti_rt.tpl
- tests/template/object/rpt.tpl
- tests/template/object/rt.tpl
> add RPT/RT object

- src/payload/req/nodoAttivaRPT.php
- src/payload/req/nodoInviaRT.php
- src/payload/req/nodoVerificaRPT.php
- src/payload/resp/nodoAttivaRPT.php
- src/payload/resp/nodoInviaRT.php
- src/payload/resp/nodoVerificaRPT.php
- tests/payload/req/nodoAttivaRPTTest.php
- tests/payload/req/nodoInviaRTTest.php
- tests/payload/req/nodoVerificaRPTTest.php
- tests/payload/resp/nodoAttivaRPTTest.php
- tests/payload/resp/nodoInviaRTTest.php
- tests/payload/resp/nodoVerificaRPTTest.php
- tests/phpunit.xml
- tests/template/fault/nodoAttivaRPT.tpl
- tests/template/fault/nodoInviaRT.tpl
- tests/template/fault/nodoVerificaRPT.tpl
- tests/template/req/nodoAttivaRPT.tpl
- tests/template/req/nodoInviaRT.tpl
- tests/template/req/nodoVerificaRPT.tpl
- tests/template/resp/nodoAttivaRPT.tpl
- tests/template/resp/nodoInviaRT.tpl
- tests/template/resp/nodoVerificaRPT.tpl
> add nodoVerificaRPT, nodoAttivaRPT, nodoInviaRT

- src/payload/req/paaAttivaRPT.php
- src/payload/req/paaInviaRT.php
- src/payload/req/paaVerificaRPT.php
- src/payload/resp/paaAttivaRPT.php
- src/payload/resp/paaInviaRT.php
- src/payload/resp/paaVerificaRPT.php
- tests/payload/req/paaAttivaRPTTest.php
- tests/payload/req/paaInviaRTTest.php
- tests/payload/req/paaVerificaRPTTest.php
- tests/payload/resp/paaAttivaRPTTest.php
- tests/payload/resp/paaInviaRTTest.php
- tests/payload/resp/paaVerificaRPTTest.php
- tests/phpunit.xml
- tests/template/fault/paaAttivaRPT.tpl
- tests/template/fault/paaInviaRT.tpl
- tests/template/fault/paaVerificaRPT.tpl
- tests/template/req/paaAttivaRPT.tpl
- tests/template/req/paaInviaRT.tpl
- tests/template/req/paaVerificaRPT.tpl
- tests/template/resp/paaAttivaRPT.tpl
- tests/template/resp/paaInviaRT.tpl
- tests/template/resp/paaVerificaRPT.tpl
> add paaVerificaRPT, paaAttivaRPT, paaInviaRT

- src/payload/req/nodoInviaRPT.php
- src/payload/resp/nodoInviaRPT.php
- tests/payload/req/nodoInviaRPTTest.php
- tests/payload/resp/nodoInviaRPTTest.php
- tests/phpunit.xml
- tests/template/fault/nodoInviaRPT.tpl
- tests/template/req/nodoInviaRPT.tpl
- tests/template/resp/nodoInviaRPT.tpl
> add nodoInviaRPT

- src/payload/req/nodoInviaCarrelloRPT.php
- src/payload/resp/nodoInviaCarrelloRPT.php
- tests/payload/req/nodoInviaCarrelloRPTTest.php
- tests/payload/resp/nodoInviaCarrelloRPTTest.php
- tests/phpunit.xml
- tests/template/fault/nodoInviaCarrelloRPT.tpl
- tests/template/req/nodoInviaCarrelloRPT.tpl
- tests/template/resp/nodoInviaCarrelloRPT.tpl
> add nodoInviaCarrelloRPT

- src/payload/req/pspInviaCarrelloRPT.php
- src/payload/req/pspInviaCarrelloRPTCarte.php
- src/payload/resp/pspInviaCarrelloRPT.php
- src/payload/resp/pspInviaCarrelloRPTCarte.php
- tests/payload/req/pspInviaCarrelloRPTCarteTest.php
- tests/payload/req/pspInviaCarrelloRPTTest.php
- tests/payload/resp/pspInviaCarrelloRPTCarteTest.php
- tests/payload/resp/pspInviaCarrelloRPTTest.php
- tests/phpunit.xml
- tests/template/fault/pspInviaCarrelloRPT.tpl
- tests/template/fault/pspInviaCarrelloRPTCarte.tpl
- tests/template/req/pspInviaCarrelloRPT.tpl
- tests/template/req/pspInviaCarrelloRPTCarte.tpl
- tests/template/resp/pspInviaCarrelloRPT.tpl
- tests/template/resp/pspInviaCarrelloRPTCarte.tpl
> add pspInviaCarrelloRPT, pspInviaCarrelloRPTCarte

- src/Event.php
> add Event class

- composer.json
- src/Payment.php
> add payment object

- helm/Chart.lock
- helm/Chart.yaml
- helm/values-dev.yaml
- helm/values-prod.yaml
- helm/values-uat.yaml
Update helm chart to 7.5 version
Update helm chart to 7.5 version
helm template command
> fix: update helm chart version to 7.5
